---
- name: Install prerequisites
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - gpg
      - wget
- name: Remove legacy haproxy.debian.net repo
  ansible.builtin.apt_repository:
    repo: deb http://haproxy.debian.net bookworm-backports-3.1 main
    state: absent
- name: Create keyrings directory
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: "0755"
- name: Add HAProxy Technologies GPG key
  ansible.builtin.get_url:
    url: https://pks.haproxy.com/linux/community/RPM-GPG-KEY-HAProxy
    dest: /usr/share/keyrings/HAPROXY-key-community.asc
    mode: "0644"
- name: Add HAProxy performance (AWS-LC) apt repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/HAPROXY-key-community.asc] https://www.haproxy.com/download/haproxy/performance/debian/ha33 trixie main"
    state: present
    filename: haproxy
- name: Install haproxy with AWS-LC
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - haproxy-awslc
- name: Make sure certificate dir exists
  ansible.builtin.file:
    path: /etc/certificates
    state: directory
    mode: "0755"
- name: Make sure errors directory exists
  ansible.builtin.file:
    path: /etc/haproxy/errors
    state: directory
    mode: "0755"
- name: Copy error pages
  loop:
    - 400
    - 429
    - 500
    - 502
    - 503
    - 504
    - default
  notify: "Reload haproxy"
  ansible.builtin.copy:
    src: files/{{ item }}.html
    dest: /etc/haproxy/errors/{{ item }}.http
    mode: "0644"
- name: Download diffie-hellman parameters from mozilla
  ansible.builtin.get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: /var/lib/dhparam
    mode: '0644'
    force: true
- name: Set lb_hostvars equal to hostvars if not already set
  check_mode: false
  ansible.builtin.set_fact:
    haproxy_lb_hostvars: "{{ hostvars }}"
  when: haproxy_lb_hostvars is not defined
- name: Generate proxy configs for verification
  notify: "Reload haproxy"
  ansible.builtin.template:
    src: templates/haproxy.conf.j2
    dest: /tmp/haproxy.cfg.new
    mode: "0644"
  register: haproxy_lb_genconfig
- name: Generate allowlist
  notify: "Reload haproxy"
  ansible.builtin.template:
    src: templates/allowlist.acl.j2
    dest: /etc/haproxy/allowlist.acl
    mode: "0644"
- name: Verify proxy configs # noqa: no-handler
  ansible.builtin.command:
    cmd: haproxy -c -V -f /tmp/haproxy.cfg.new
  when: haproxy_lb_genconfig.changed
- name: Copy the verified config # noqa: no-handler
  ansible.builtin.command:
    cmd: cp /tmp/haproxy.cfg.new /etc/haproxy/haproxy.cfg
  when: haproxy_lb_genconfig.changed
- name: Ensure vector config dir exists
  ansible.builtin.file:
    path: /etc/vector
    state: directory
- name: Add the scrape to vector
  ansible.builtin.copy:
    src: vector.yaml
    dest: /etc/vector/haproxy.yaml
  notify: Vector-reload
