- name: Ensure user {{ extra_user }} is present
  ansible.builtin.user:
    name: "{{ extra_user }}"
    comment: "User {{ extra_user }}"
    shell: /bin/bash
    create_home: yes

- name: Fetch public key from GitHub
  ansible.builtin.get_url:
    url: "https://github.com/{{ extra_user }}.keys"
    dest: "/tmp/{{ extra_user }}.keys"
    mode: '0644'

- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "/home/{{ extra_user }}/.ssh"
    state: directory
    owner: "{{ extra_user }}"
    group: "{{ extra_user }}"
    mode: '0700'

- name: Add public keys from GitHub to authorized_keys
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/{{ extra_user }}.keys"
    dest: "/home/{{ extra_user }}/.ssh/authorized_keys"
    owner: "{{ extra_user }}"
    group: "{{ extra_user }}"
    mode: '0600'
    force: yes

- name: Add public keys from NetBox to authorized_keys
  ansible.builtin.copy:
    remote_src: true
    content: "{{ ssh_keys[extra_user] }}\n"
    dest: "/home/{{ extra_user }}/.ssh/authorized_keys"
    owner: "{{ extra_user }}"
    group: "{{ extra_user }}"
    mode: '0600'
    force: yes

- name: Allow user {{ extra_user }} passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: "{{ extra_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: Clean up temporary files
  ansible.builtin.file:
    path: "/tmp/{{ extra_user }}.keys"
    state: absent
